#!/bin/bash
#
# Simple testing script for querier.c
#
# Tim (Kyoung Tae) Kim, CS50 Lab6
# May, 2021

# various invalid arguments (zero, one, three)
./querier 
./querier ~/cs50-dev/shared/tse/output/letters-0
./querier ~/cs50-dev/shared/tse/output/letters-0 letters-0.index letters-0.index-1

# invalid pageDirectory (non-existent, not crawler)
./querier ~/cs50-dev/non/existent/dir/letters-0 letters-0.index
./querier ~/cs50-dev/shared/COVID-19 letters-0.index

# invalid indexFilename (non-existent)
./querier ~/cs50-dev/shared/tse/output/letters-0 ./non/existent/letters-0.index 

# syntax errors & invalid queries
cat "./examples/syntax.txt" | ./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 

# printing clean query
echo " tHIs     seNTEnce  iS  nOrmAL  " | ./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 

# print nothing is query is empty
echo "          " | ./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 
    
# print no documents match if query returns nothing
echo "dirichlet" | ./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 

# equivalent single-word examples
echo "Magnificent" | ./querier ~/cs50-dev/shared/tse/output/toscrape-2 ~/cs50-dev/shared/tse/output/toscrape-2.index 

echo "magnificent" | ./querier ~/cs50-dev/shared/tse/output/toscrape-2 ~/cs50-dev/shared/tse/output/toscrape-2.index 

echo "         magnificent" | ./querier ~/cs50-dev/shared/tse/output/toscrape-2 ~/cs50-dev/shared/tse/output/toscrape-2.index 

# equivalent two-word examples / implicit and explicit 'and' are equivalent
echo "John Wick" | ./querier ~/cs50-dev/shared/tse/output/toscrape-1 ~/cs50-dev/shared/tse/output/toscrape-1.index 

echo "john wick" | ./querier ~/cs50-dev/shared/tse/output/toscrape-1 ~/cs50-dev/shared/tse/output/toscrape-1.index 

echo "john and wick" | ./querier ~/cs50-dev/shared/tse/output/toscrape-1 ~/cs50-dev/shared/tse/output/toscrape-1.index 

echo "          john      AND    wick    " | ./querier ~/cs50-dev/shared/tse/output/toscrape-1 ~/cs50-dev/shared/tse/output/toscrape-1.index 

# difference between 'and' vs 'or' queries
echo "play and ted" |./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 

echo "play or ted" |./querier ~/cs50-dev/shared/tse/output/wikipedia-1 ~/cs50-dev/shared/tse/output/wikipedia-1.index 

# testing with fuzzquery that generate random queries (index, no of queries, seed)
declare -i nquery
declare -i seed
nquery=10
seed=0
./fuzzquery ~/cs50-dev/shared/tse/output/toscrape-2.index $nquery $seed | ./querier ~/cs50-dev/shared/tse/output/toscrape-2 ~/cs50-dev/shared/tse/output/toscrape-2.index

# run valgrind with queries generated by fuzzquery 
./fuzzquery ~/cs50-dev/shared/tse/output/toscrape-2.index $nquery $seed | valgrind -v --leak-check=full --show-leak-kinds=all ./querier ~/cs50-dev/shared/tse/output/toscrape-2 ~/cs50-dev/shared/tse/output/toscrape-2.index
